In [1]:
#loading in relevant libraries 
import pandas as pd

In [2]:
#loading & viewing the dataset 
police=pd.read_csv('Police.csv')
police.head()

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [4]:
#basic EDA
police.shape

(65535, 15)

In [5]:
police.dtypes

stop_date              object
stop_time              object
country_name          float64
driver_gender          object
driver_age_raw        float64
driver_age            float64
driver_race            object
violation_raw          object
violation              object
search_conducted         bool
search_type            object
stop_outcome           object
is_arrested            object
stop_duration          object
drugs_related_stop       bool
dtype: object

In [6]:
#summary statistics table
police.describe()

       country_name  driver_age_raw    driver_age
count           0.0    61481.000000  61228.000000
mean            NaN     1967.791106     34.148984
std             NaN      121.050106     12.760710
min             NaN        0.000000     15.000000
25%             NaN     1965.000000     23.000000
50%             NaN     1978.000000     31.000000
75%             NaN     1985.000000     43.000000
max             NaN     8801.000000     88.000000

In [7]:
#obviously some nulls, going to dig in from here
police.isnull().sum()

stop_date                 0
stop_time                 0
country_name          65535
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

In [11]:
#jesus, ton of nulls, country name entire column is missing too 
#removing that colum
police.drop(columns= 'country_name', inplace=True)

In [12]:
#checking to see if column is gone
police

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12/7/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/7/2012,0:30,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [13]:
#looks good, still gotta deal with other nulls 
police.isnull().sum()

stop_date                 0
stop_time                 0
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

In [14]:
#creating new dataframe to drop nulls
df=police.dropna()

In [15]:
#checking for nulls in newly created dataframe
df.isnull().sum()

stop_date             0
stop_time             0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
dtype: int64

In [16]:
#looks good, taking a peek at cleaned data
df

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
24,8/28/2005,1:00,M,1979.0,26.0,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,16-30 Min,False
40,10/1/2005,0:00,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,16-30 Min,True
41,10/1/2005,0:00,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,30+ Min,True
80,10/2/2005,9:30,M,1975.0,30.0,White,Speeding,Speeding,True,Incident to Arrest,Arrest Driver,True,30+ Min,False
106,10/3/2005,14:00,M,1978.0,27.0,Black,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,16-30 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65254,11/25/2012,0:33,M,1984.0,28.0,White,Call for Service,Other,True,Inventory,Arrest Driver,True,0-15 Min,False
65358,11/29/2012,1:06,M,1986.0,26.0,White,Speeding,Speeding,True,Probable Cause,Citation,False,0-15 Min,False
65408,11/30/2012,22:37,F,1986.0,26.0,Hispanic,Speeding,Speeding,True,Reasonable Suspicion,Citation,False,30+ Min,True
65409,11/30/2012,23:40,M,1980.0,32.0,White,Other Traffic Violation,Moving violation,True,Reasonable Suspicion,Citation,False,30+ Min,False
65499,12/5/2012,23:13,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,True,Probable Cause,Warning,False,0-15 Min,True

In [18]:
#going to see if men or women were stopped more often by the police for speeding violations
#gotta consider gender and violation columns respectively
df[df.violation == 'Speeding'].driver_gender.value_counts()

M    693
F    102
Name: driver_gender, dtype: int64

In [19]:
#does gender affect who gets searched during a stop?
df.groupby('driver_gender').search_conducted.sum()

driver_gender
F     366
M    2111
Name: search_conducted, dtype: int64

In [ ]:
#males are searched more often but also appear to be stopped more often as well

In [20]:
#finiding the mean stop duration
df.describe()

       driver_age_raw   driver_age
count     2477.000000  2477.000000
mean      1978.096084    30.544207
std         10.590428    10.414790
min       1930.000000    15.000000
25%       1971.000000    22.000000
50%       1981.000000    27.000000
75%       1986.000000    37.000000
max       1994.000000    79.000000

In [21]:
#maybe stop duration isn't the right datatype?
df.dtypes

stop_date              object
stop_time              object
driver_gender          object
driver_age_raw        float64
driver_age            float64
driver_race            object
violation_raw          object
violation              object
search_conducted         bool
search_type            object
stop_outcome           object
is_arrested            object
stop_duration          object
drugs_related_stop       bool
dtype: object

In [22]:
#okay, so stop duration is essentially a categorical object in the dataset
#want to understand distribution first, then going to correct 
df.stop_duration.value_counts()

16-30 Min    1123
30+ Min       740
0-15 Min      614
Name: stop_duration, dtype: int64

In [23]:
#changing stop duration column
df['stop_duration']=df['stop_duration'].map({'0-15 Min':7.5, '16-30 Min':24, '30+ Min':45})

C:\Users\Cameron\AppData\Local\Temp\ipykernel_20756\3993605464.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['stop_duration']=df['stop_duration'].map({'0-15 Min':7.5, '16-30 Min':24, '30+ Min':45})

In [24]:
#seeing if performed correctly
df

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
24,8/28/2005,1:00,M,1979.0,26.0,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,24.0,False
40,10/1/2005,0:00,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,24.0,True
41,10/1/2005,0:00,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,45.0,True
80,10/2/2005,9:30,M,1975.0,30.0,White,Speeding,Speeding,True,Incident to Arrest,Arrest Driver,True,45.0,False
106,10/3/2005,14:00,M,1978.0,27.0,Black,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,24.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65254,11/25/2012,0:33,M,1984.0,28.0,White,Call for Service,Other,True,Inventory,Arrest Driver,True,7.5,False
65358,11/29/2012,1:06,M,1986.0,26.0,White,Speeding,Speeding,True,Probable Cause,Citation,False,7.5,False
65408,11/30/2012,22:37,F,1986.0,26.0,Hispanic,Speeding,Speeding,True,Reasonable Suspicion,Citation,False,45.0,True
65409,11/30/2012,23:40,M,1980.0,32.0,White,Other Traffic Violation,Moving violation,True,Reasonable Suspicion,Citation,False,45.0,False
65499,12/5/2012,23:13,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,True,Probable Cause,Warning,False,7.5,True

In [25]:
#now, going to find mean stop duration
df.describe()

       driver_age_raw   driver_age  stop_duration
count     2477.000000  2477.000000    2477.000000
mean      1978.096084    30.544207      26.183690
std         10.590428    10.414790      13.947888
min       1930.000000    15.000000       7.500000
25%       1971.000000    22.000000      24.000000
50%       1981.000000    27.000000      24.000000
75%       1986.000000    37.000000      45.000000
max       1994.000000    79.000000      45.000000

In [ ]:
#the mean stop duration is about 26 minutes give or take

In [26]:
#last, i want to compare the age distribtuion for each violation
df.groupby('violation').driver_age.describe()

                     count       mean        std   min   25%   50%   75%   max
violation
Equipment            539.0  29.254174   9.568786  16.0  22.0  26.0  34.0  70.0
Moving violation     690.0  32.221739  11.302226  15.0  23.0  29.0  40.0  79.0
Other                164.0  33.073171  11.775279  17.0  23.0  30.0  42.0  65.0
Registration/plates  289.0  31.387543  10.667415  16.0  23.0  29.0  37.0  65.0
Speeding             795.0  29.134591   9.405944  17.0  22.0  26.0  33.0  68.0